import { mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import type { TopologyAnalysis } from './analyze.ts'
import type { PrewarmReport } from './prewarm.ts'

/**
 * Emit a compile artifact under `.grove/compiled/<name>/`.
 *
 * Files produced:
 * - `manifest.json`  — full topology analysis + cost projection.
 * - `prewarm.json`   — `(tool, input, output)` triples produced by running
 *                      each deterministic tool against its declared
 *                      `examples`. The runtime cache loads these eagerly,
 *                      so the cold-start "first call pays" tax disappears.
 * - `index.ts`       — small TS shim that re-exports `start` and the
 *                      manifest. Convenient when consumers want a single
 *                      import to feed into bundlers.
 */
export function emit(
  name: string,
  analysis: TopologyAnalysis,
  prewarm?: PrewarmReport,
  outDir = join(process.cwd(), '.grove', 'compiled'),
): { dir: string; files: string[] } {
  const dir = join(outDir, name)
  mkdirSync(dir, { recursive: true })

  const manifest = {
    version: 1,
    generatedAt: new Date().toISOString(),
    analysis,
    cacheStrategy: 'content-hash-by-tool-input',
    prewarm: prewarm
      ? { entries: prewarm.entries.length, skipped: prewarm.skipped.length }
      : undefined,
  }
  const manifestPath = join(dir, 'manifest.json')
  writeFileSync(manifestPath, JSON.stringify(manifest, null, 2))

  const files = [manifestPath]
  if (prewarm) {
    const prewarmPath = join(dir, 'prewarm.json')
    writeFileSync(prewarmPath, JSON.stringify(prewarm, null, 2))
    files.push(prewarmPath)
  }

  const shim = `// Auto-generated by @vyntral/grove-compiler — do not edit.
// Re-exports start() from the runtime so consumers can route their
// runtime entrypoint through the compile artifact.
import { start } from '@vyntral/grove-runtime'
import manifest from './manifest.json' with { type: 'json' }

export { manifest }
export { start }
`
  const shimPath = join(dir, 'index.ts')
  writeFileSync(shimPath, shim)
  files.push(shimPath)

  return { dir, files }
}
